spring.application.name=backend

spring.mongodb.uri= mongodb://localhost:27017/poker_ledger?replicaSet=rs0

spring.data.mongodb.auto-index-creation=true

jwt.secret= "a9a1aa96d8f6ec3ecae3b51d8102e1dffb94720fbebef85336c5397f764f552d"
jwt.expiration-ms= 86400000

